### PR TITLE
fix stoken generation

### PR DESCRIPTION
**Pull request by HermogenesBatista**

### CODE REVIEW

**Comment by hthieu1110** [comment]
I've seen your fix :) it's cool. Could you pls juste remove some #print and it'll be perfect :)

**Comment by hthieu1110** [comment]
thanks :)

**Comment by HermogenesBatista** [comment]
It's Done!

**Comment by hthieu1110** [comment]
Thanks so much @HermogenesBatista :+1:

**Comment by HermogenesBatista** [comment]
You are welcome! :+1:

**Pull request merged**
